### ISSUE TITLE
Building a Calculator Tutorial won't work with Go 1.12

### ISSUE THREAD

**Issue by MakotoE** [elliotforbes/tutorialedge-v2#16]
Thanks to "Building a Calculator Tutorial", I'm quickly learning the WebAssembly basics. I just updated to Go 1.12, and noticed that the `syscall/js` library as changed significantly, and the tutorial will not work if Go 1.12 is used.

I wanted to make a pull request to update the tutorial, but I first wanted to check on how you handle language version changes. The instructions in the YouTube video will be slightly different than the text with my changes, so I'm not sure if you wanted them to match or if it's okay if they differed.

**Comment by ff4f01** [comment]
@MakotoE Well I've just noticed that too.

It seems like `FuncOf` should be used instead of `NewCallback` as of go1.12, since `Callback` has been changed to `Func`. While the document clarifies that we need to prepare go1.11, #15 was accepted that I think the tutorial can be re-written in newer version of language.
